### ISSUE TITLE
replacing @everyone mentions

### ISSUE THREAD

**Issue by idontlikecheese** [crimilo/Discord-Mirror#3]
Unable to replace @everyone mentions.

**Comment by crimilo** [comment]
> Unable to replace @everyone mentions.

You can replace @everyone mentions. You simply have to configure it like any other role. The ID of the @everyone role is the same of the server ID.

**Comment by crimilo** [comment]
No one should have had a problem with this, but I just fixed a bug where if the message contained only a mention and no other text, the mention replacement would not occur. Re-clone the repository to get the latest version.

Anyway, this is an example of how to mention **@everyone** from the server with ID: `123` to the server with ID: `456`:
```json
"mentions": {
    "456": [
      {
        "original": "123",
        "replaced": "456"
      }
    ]
  }
  ```

**Comment by idontlikecheese** [comment]
I re-configured and tried it again;
when copying from server 1 to server 2, it's currently configured like this:

`"mentions": {
    "server id 1": [
      {
        "original": "server id 1",
        "replaced": "role id 2"
      }
    ]
  }`
  
  
  This still does not work, this just takes the @everyone mention from server 1 and copies it to server 2, without changing it.
  
  
  Extra notes:
 * I do not have this issue when replacing regular @role mentions.
 * Independently from what @mention I copy, I have to use the server id from server 1 at line 2, otherwise it just outputs @deleted-role.
  *I'm not trying to change the original @everyone mention to a new @everyone mention, I'm trying to change an @everyone mention to a @role mention.

**Comment by crimilo** [comment]
> I re-configured and tried it again;
> 
> when copying from server 1 to server 2, it's currently configured like this:
> 
> > "mentions": {
> > "server id 1": [
> > {
> > "original": "server id 1",
> > "replaced": "role id 2"
> > }
> > ]
> > }
> 
> This still does not work, this just takes the @everyone mention from server 1 and copies it to server 2, without changing it.
> 
> Extra notes:
> 
>     * I do not have this issue when replacing regular @ROLE mentions.
> 
>     * Independently from what @mention I copy, I have to use the server id from server 1 at line 2, otherwise it just outputs @deleted-role.
> 
>     * I'm not trying to change the original @everyone mention to a new @everyone mention, I'm trying to change an @everyone mention to an @ROLE mention.

Your configuration is wrong.
If you want to replace **@everyone** with **@ExampleRole** and you have the following scenario:
| Server   | Server Id | Role         | Role Id |
|-------------|----------|-----------------------|---------|
| Server 1 | 1         | @everyone         | 1       |
| Server 2 | 2         | @everyone         | 2       |
| Server 2 | 2         | @ExampleRole  | 3       |

You need to configure it as the following:
```json
"mentions": {
    "2": [
      {
        "original": "1",
        "replaced": "3"
      }
    ]
  }
  ```
  
  If a message in the server 1 contains **@everyone**, the mirrored message on server 2 will replace **@everyone** with **@ExampleRole**.

**Comment by idontlikecheese** [comment]
These are all the different configurations that I've tried today and what the results were, based on the following scenario:

| Server  | Server Id | Role  | Role Id |
| ------------- | ------------- | ------------- | ------------- |
| Server 1  | 1  | @everyone  | 1  |
| Server 2  | 2  | @everyone  | 2  |
| Server 1  | 1  | @ExampleRole  | 3  |
| Server 2  | 2  | @ExampleRole2  | 4  |



Configuration 1:
(same as the one that u mentioned)
Output: @everyone ping, ignores replacement
```
"mentions": {
    "2": [
      {
        "original": "1",
        "replaced": "4"
      }
    ]
  }
```


Configuration 2:
Output: @deleted-role
```
"mentions": {
    "2": [
      {
        "original": "3",
        "replaced": "4"
      }
    ]
  }
```



Configuration 3: 
(only one that worked, doesn't work with @everyone ping -> see configuration 4)
Output: @ExampleRole2, role id 4
```
"mentions": {
    "1": [
      {
        "original": "3",
        "replaced": "4"
      }
    ]
  }
```

Configuration 4:
Output: @everyone ping, ignores replacement
```
"mentions": {
    "1": [
      {
        "original": "1",
        "replaced": "4"
      }
    ]
  }
```

Notes:
* I use the latest version of the Discord-Mirrorer.
* I tried these configurations twice to make sure everything that I said is indeed correct.
* As u can see above: the only way that it successfully managed to replace the @Mention was when the original mention was an @ExampleRole, and when the server id used was the server id from the original server.
